version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Shanghai
    labels: [dependencies]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:30"
      timezone: Asia/Shanghai
    labels: [dependencies, github-actions]
    open-pull-requests-limit: 5
